package com.crio.starter.model;

import javax.validation.constraints.NotNull;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.Transient;
import org.springframework.data.mongodb.core.mapping.Document;

// Java class that maps to Mongo collection.

@Data
@Document(collection = "memes")
@NoArgsConstructor
public class MemeEntity {

    @Transient
    public static final String SEQUENCE_NAME = "id_Generator";

    //@Id is a string representation of ObjectId, which can be auto-generated by MongoDB.
    @Id
    private String memeid;

    @NotNull
    private String personName;

    @NotNull
    private String memeCaption;
    
    @NotNull
    private String imageUrl;
    
}